// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by arrgen. DO NOT EDIT.

package gentypes

import (
	"github.com/apache/arrow-go/v18/arrow"
	"github.com/apache/arrow-go/v18/arrow/array"
	"github.com/apache/arrow-go/v18/arrow/memory"
)

// metricArrowSchema is the Arrow schema of Metric, resolved from its arrow
// struct tags at generate time.
var metricArrowSchema = arrow.NewSchema([]arrow.Field{
	{Name: "day", Type: arrow.FixedWidthTypes.Date32, Nullable: false},
	{Name: "host", Type: arrow.BinaryTypes.String, Nullable: false},
	{Name: "cpu", Type: arrow.PrimitiveTypes.Float64, Nullable: false},
	{Name: "value", Type: arrow.PrimitiveTypes.Float64, Nullable: true},
}, nil)

// MetricSchema returns the Arrow schema encoded by MetricAppender. It is
// equal to the schema arreflect.InferSchema[Metric] infers at runtime.
func MetricSchema() *arrow.Schema { return metricArrowSchema }

// MetricAppender converts Metric values into Arrow record batches
// without reflection: the struct tags were read when this file was generated,
// so appending a row is a handful of direct field loads into typed builders.
//
// It is not safe for concurrent use. Release it when done.
type MetricAppender struct {
	rb  *array.RecordBuilder
	b0  *array.Date32Builder
	b1  *array.StringBuilder
	b2  *array.Float64Builder
	b3  *array.Float64Builder
	err error
}

// NewMetricAppender returns an appender that builds Metric batches with mem,
// or memory.DefaultAllocator when mem is nil.
//
// The typed field builders are resolved once here rather than per row, so
// Append does no type assertions at all.
func NewMetricAppender(mem memory.Allocator) *MetricAppender {
	if mem == nil {
		mem = memory.DefaultAllocator
	}
	rb := array.NewRecordBuilder(mem, metricArrowSchema)
	return &MetricAppender{
		rb: rb,
		b0: rb.Field(0).(*array.Date32Builder),
		b1: rb.Field(1).(*array.StringBuilder),
		b2: rb.Field(2).(*array.Float64Builder),
		b3: rb.Field(3).(*array.Float64Builder),
	}
}

// Schema returns the schema of the batches this appender builds.
func (a *MetricAppender) Schema() *arrow.Schema { return metricArrowSchema }

// RecordBuilder returns the underlying builder, for callers that need an Arrow
// API this appender does not wrap. Appending through it directly is allowed as
// long as every column stays the same length.
func (a *MetricAppender) RecordBuilder() *array.RecordBuilder { return a.rb }

// Reserve pre-allocates room for n more rows in every column. Reserving before
// a run of Appends is what keeps the append path free of allocations.
func (a *MetricAppender) Reserve(n int) { a.rb.Reserve(n) }

// Len reports the number of rows appended since the last NewRecordBatch.
func (a *MetricAppender) Len() int { return a.rb.Field(0).Len() }

// Append appends one row. v is read synchronously and never retained, so a
// caller streaming rows can reuse a single Metric variable across calls.
func (a *MetricAppender) Append(v *Metric) {
	a.b0.Append(arrow.Date32FromTime(v.Day))
	a.b1.Append(v.Host)
	a.b2.Append(v.CPU)
	if v.Value == nil {
		a.b3.AppendNull()
	} else {
		a.b3.Append(*v.Value)
	}
}

// AppendSlice appends every element of vs, reserving room for them up front.
func (a *MetricAppender) AppendSlice(vs []Metric) {
	a.rb.Reserve(len(vs))
	for i := range vs {
		a.Append(&vs[i])
	}
}

// NewRecordBatch snapshots the appended rows into a record batch and resets the
// appender for the next batch. The caller owns the batch and must Release it.
func (a *MetricAppender) NewRecordBatch() arrow.RecordBatch { return a.rb.NewRecordBatch() }

// Err returns the first error an Append hit, or nil. Only dictionary columns
// can fail, so an appender over a schema without one always returns nil.
//
// The error is sticky: NewRecordBatch does not clear it, because a batch built
// after a failed append is missing a value in that column.
func (a *MetricAppender) Err() error { return a.err }

// Release releases the appender's builders.
func (a *MetricAppender) Release() { a.rb.Release() }

// MetricRecordBatch builds one record batch holding every element of vs. It is the
// generated equivalent of arreflect.RecordFromSlice[Metric](vs, mem) and
// produces an identical batch. The caller owns the batch and must Release it.
func MetricRecordBatch(mem memory.Allocator, vs []Metric) (arrow.RecordBatch, error) {
	a := NewMetricAppender(mem)
	defer a.Release()
	a.AppendSlice(vs)
	if err := a.Err(); err != nil {
		return nil, err
	}
	return a.NewRecordBatch(), nil
}
