// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package arrgen_test

import (
	"bytes"
	"flag"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/apache/arrow-go/arrgen"
	"github.com/apache/arrow-go/v18/arrow"
	"github.com/apache/arrow-go/v18/arrow/array/arreflect"
	"github.com/apache/arrow-go/v18/arrow/decimal128"
	"github.com/apache/arrow-go/v18/arrow/decimal256"
)

var update = flag.Bool("update", false, "rewrite the golden files instead of comparing against them")

const goldenPath = "testdata/basic.golden"

// TestGenerateGolden compares the whole emitted file against a checked-in
// copy. A golden file is worth more than a set of assertions about fragments
// here: what ships to users is the file, and a reviewer reading the diff of
// this one can see exactly what a generator change does to their code.
func TestGenerateGolden(t *testing.T) {
	header, err := os.ReadFile("license_header.txt")
	if err != nil {
		t.Fatalf("reading license header: %v", err)
	}
	got, err := arrgen.Generate(arrgen.Config{
		Dir:    "testdata/basic",
		Types:  []string{"Metric", "reading"},
		Header: string(header),
	})
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}

	if *update {
		if err := os.WriteFile(goldenPath, got, 0o644); err != nil {
			t.Fatalf("writing golden: %v", err)
		}
		return
	}

	want, err := os.ReadFile(goldenPath)
	if err != nil {
		t.Fatalf("reading golden: %v (run: go test ./... -update)", err)
	}
	if !bytes.Equal(got, want) {
		t.Errorf("generated output differs from %s; rerun with -update to accept\n--- got ---\n%s", goldenPath, got)
	}
}

// TestGenerateIsDeterministic guards the property the drift check in
// internal/gentypes depends on: the same package in, the same bytes out.
func TestGenerateIsDeterministic(t *testing.T) {
	cfg := arrgen.Config{Dir: "testdata/basic", Types: []string{"Metric", "reading"}}
	first, err := arrgen.Generate(cfg)
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}
	second, err := arrgen.Generate(cfg)
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}
	if !bytes.Equal(first, second) {
		t.Error("two runs over the same package produced different output")
	}
}

// TestGenerateHeaderOptional checks that the generated-code marker leads the
// file when no header is configured, which is what tools look for.
func TestGenerateHeaderOptional(t *testing.T) {
	got, err := arrgen.Generate(arrgen.Config{Dir: "testdata/basic", Types: []string{"Metric"}})
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}
	const marker = "// Code generated by arrgen. DO NOT EDIT."
	if !bytes.HasPrefix(got, []byte(marker)) {
		t.Errorf("output does not start with %q:\n%s", marker, first(got, 200))
	}
}

// TestGenerateRejects is the contract that arrgen never drops a column it does
// not understand. Every entry here is a struct that would otherwise be encoded
// wrongly, silently, or not at all.
func TestGenerateRejects(t *testing.T) {
	tests := []struct {
		typ  string
		want string
	}{
		{"Embedded", "embedded fields are not supported"},
		{"Nested", "nested struct column"},
		{"SliceField", "list column for []int64 is not supported"},
		{"ArrayField", "is not supported"},
		{"MapField", "is not supported"},
		{"NamedScalar", "named type"},
		{"UnknownOption", `unknown option "nope"`},
		{"BadDecimalTag", "is not an integer"},
		{"ShortDecimalTag", "expected decimal(precision,scale)"},
		{"DuplicateNames", `both map to column "same"`},
		{"TemporalOnInt", "only valid on a time.Time field"},
		{"DecimalOnInt", "only valid on a decimal field"},
		{"DictOnBool", "dict is not supported on bool"},
		{"ViewOnInt", "view has no effect"},
		{"LargeOnInt", "large has no effect"},
		{"RunEndEncoded", "ree is not supported"},
		{"DictAndView", "at most one of dict, view, ree"},
		{"DictAndLarge", "cannot be combined with large"},
		{"BareTime", "one of the date32, date64, time32 or time64 tags"},
		{"TimestampTime", "one of the date32, date64, time32 or time64 tags"},
		{"BareDecimal128", "decimal128.Num needs a decimal(precision,scale) tag"},
		{"BareDecimal256", "decimal256.Num needs a decimal(precision,scale) tag"},
		{"NoColumns", "no Arrow columns"},
		{"TimeSlice", "list column"},
		{"NotAStruct", "not a struct type"},
		{"Absent", "type not found"},
	}

	for _, tt := range tests {
		t.Run(tt.typ, func(t *testing.T) {
			_, err := arrgen.Generate(arrgen.Config{Dir: "testdata/errors", Types: []string{tt.typ}})
			if err == nil {
				t.Fatalf("Generate(%s) succeeded, want an error mentioning %q", tt.typ, tt.want)
			}
			if !strings.Contains(err.Error(), tt.want) {
				t.Errorf("Generate(%s) error = %q, want it to mention %q", tt.typ, err, tt.want)
			}
			if !strings.Contains(err.Error(), tt.typ) {
				t.Errorf("Generate(%s) error = %q, want it to name the type", tt.typ, err)
			}
		})
	}
}

// TestGenerateNamesTheField checks that a rejection points at the field, not
// just the struct: on a wide struct that is the difference between a fix and a
// hunt.
func TestGenerateNamesTheField(t *testing.T) {
	_, err := arrgen.Generate(arrgen.Config{Dir: "testdata/errors", Types: []string{"Nested"}})
	if err == nil {
		t.Fatal("Generate succeeded, want an error")
	}
	if !strings.Contains(err.Error(), "field Field") {
		t.Errorf("error = %q, want it to name the offending field", err)
	}
}

// TestGenerateRejectsCollidingTypes covers two types in one file whose
// generated names would clash - the sort of thing that would otherwise surface
// as a compile error in code the user never wrote.
func TestGenerateRejectsCollidingTypes(t *testing.T) {
	_, err := arrgen.Generate(arrgen.Config{Dir: "testdata/errors", Types: []string{"Collide", "collide"}})
	if err == nil {
		t.Fatal("Generate succeeded, want a collision error")
	}
	if !strings.Contains(err.Error(), "collides with") {
		t.Errorf("error = %q, want it to report the collision", err)
	}
}

func TestGenerateRejectsRepeatedType(t *testing.T) {
	_, err := arrgen.Generate(arrgen.Config{Dir: "testdata/errors", Types: []string{"Collide", "Collide"}})
	if err == nil {
		t.Fatal("Generate succeeded, want a collision error")
	}
}

// TestGenerateBeforePackageCompiles is the chicken-and-egg case: the call sites
// for the generated API are written first, so the package does not type-check
// until the generator has run. Refusing to run then would make the generator
// unusable exactly when it is needed.
func TestGenerateBeforePackageCompiles(t *testing.T) {
	got, err := arrgen.Generate(arrgen.Config{Dir: "testdata/pregen", Types: []string{"Sample"}})
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}
	if !bytes.Contains(got, []byte("func SampleRecordBatch(")) {
		t.Error("generated output does not declare SampleRecordBatch")
	}
}

// TestGenerateReportsLoadErrors checks that when a type genuinely cannot be
// resolved, the package's own compile errors come along as the likely cause
// rather than leaving the user with a bare "type not found".
func TestGenerateReportsLoadErrors(t *testing.T) {
	_, err := arrgen.Generate(arrgen.Config{Dir: "testdata/pregen", Types: []string{"Absent"}})
	if err == nil {
		t.Fatal("Generate succeeded, want an error")
	}
	if !strings.Contains(err.Error(), "does not type-check") {
		t.Errorf("error = %q, want it to surface the package's compile errors", err)
	}
}

func TestGenerateNoTypes(t *testing.T) {
	if _, err := arrgen.Generate(arrgen.Config{Dir: "testdata/basic"}); err == nil {
		t.Error("Generate with no types succeeded, want an error")
	}
}

func TestGenerateMissingPackage(t *testing.T) {
	dir := filepath.Join(t.TempDir(), "empty")
	if err := os.Mkdir(dir, 0o755); err != nil {
		t.Fatal(err)
	}
	if _, err := arrgen.Generate(arrgen.Config{Dir: dir, Types: []string{"Metric"}}); err == nil {
		t.Error("Generate in a directory with no Go files succeeded, want an error")
	}
}

// TestArreflectCannotInferStructScalars pins the upstream behavior that the
// rejections above exist for.
//
// time.Time, decimal128.Num and decimal256.Num are Go structs that Arrow models
// as scalars. arreflect's inferArrowType switches on reflect.Kind before it
// reaches the types it matches by identity, so as a struct field each one is
// resolved by inferStructType, which sees only unexported fields and yields an
// empty struct<>. arrgen refuses to generate the column Arrow means here
// because doing so would break the equivalence it promises.
//
// If arreflect learns to infer these, this test fails - which is good news, not
// a regression. It means the rejections in mapping.go can be dropped and the
// untagged spellings generated instead.
func TestArreflectCannotInferStructScalars(t *testing.T) {
	type row struct {
		Time time.Time      `arrow:"t"`
		TS   time.Time      `arrow:"ts,timestamp"`
		D128 decimal128.Num `arrow:"d128"`
		D256 decimal256.Num `arrow:"d256"`
	}

	schema, err := arreflect.InferSchema[row]()
	if err != nil {
		t.Fatalf("InferSchema: %v", err)
	}
	for i := 0; i < schema.NumFields(); i++ {
		f := schema.Field(i)
		if f.Type.ID() != arrow.STRUCT {
			t.Errorf("arreflect now infers column %q as %s rather than an empty struct; "+
				"drop the matching rejection in mapping.go and generate the column instead", f.Name, f.Type)
		}
	}
}

func first(b []byte, n int) []byte {
	if len(b) < n {
		return b
	}
	return b[:n]
}
