// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package arrgen

import "text/template"

// fileTemplate renders the whole generated file. The emitted code imports only
// arrow, arrow/array and arrow/memory (plus time, for time-of-day columns), so
// nothing a caller builds with arrgen ends up depending on arrgen itself.
var fileTemplate = template.Must(template.New("arrgen").Parse(
	`{{if .Header}}{{.Header}}

{{end}}// Code generated by arrgen. DO NOT EDIT.

package {{.Package}}

import (
{{- if .NeedTime}}
	"time"
{{end}}
	"github.com/apache/arrow-go/v18/arrow"
	"github.com/apache/arrow-go/v18/arrow/array"
	"github.com/apache/arrow-go/v18/arrow/memory"
)
{{range .Types}}
// {{.SchemaVar}} is the Arrow schema of {{.GoName}}, resolved from its arrow
// struct tags at generate time.
var {{.SchemaVar}} = arrow.NewSchema([]arrow.Field{
{{- range .Fields}}
	{Name: {{printf "%q" .Name}}, Type: {{.ArrowType}}, Nullable: {{.Nullable}}},
{{- end}}
}, nil)

// {{.SchemaFunc}} returns the Arrow schema encoded by {{.AppenderType}}. It is
// equal to the schema arreflect.InferSchema[{{.GoName}}] infers at runtime.
func {{.SchemaFunc}}() *arrow.Schema { return {{.SchemaVar}} }

// {{.AppenderType}} converts {{.GoName}} values into Arrow record batches
// without reflection: the struct tags were read when this file was generated,
// so appending a row is a handful of direct field loads into typed builders.
//
// It is not safe for concurrent use. Release it when done.
type {{.AppenderType}} struct {
	rb *array.RecordBuilder
{{- range .Fields}}
	{{.BuilderVar}} {{.BuilderType}}
{{- end}}
	err error
}

// {{.CtorName}} returns an appender that builds {{.GoName}} batches with mem,
// or memory.DefaultAllocator when mem is nil.
//
// The typed field builders are resolved once here rather than per row, so
// Append does no type assertions at all.
func {{.CtorName}}(mem memory.Allocator) *{{.AppenderType}} {
	if mem == nil {
		mem = memory.DefaultAllocator
	}
	rb := array.NewRecordBuilder(mem, {{.SchemaVar}})
	return &{{.AppenderType}}{
		rb: rb,
{{- range .Fields}}
		{{.BuilderVar}}: rb.Field({{.Index}}).({{.BuilderType}}),
{{- end}}
	}
}

// Schema returns the schema of the batches this appender builds.
func (a *{{.AppenderType}}) Schema() *arrow.Schema { return {{.SchemaVar}} }

// RecordBuilder returns the underlying builder, for callers that need an Arrow
// API this appender does not wrap. Appending through it directly is allowed as
// long as every column stays the same length.
func (a *{{.AppenderType}}) RecordBuilder() *array.RecordBuilder { return a.rb }

// Reserve pre-allocates room for n more rows in every column. Reserving before
// a run of Appends is what keeps the append path free of allocations.
func (a *{{.AppenderType}}) Reserve(n int) { a.rb.Reserve(n) }

// Len reports the number of rows appended since the last NewRecordBatch.
func (a *{{.AppenderType}}) Len() int { return a.rb.Field(0).Len() }

// Append appends one row. v is read synchronously and never retained, so a
// caller streaming rows can reuse a single {{.GoName}} variable across calls.
func (a *{{.AppenderType}}) Append(v *{{.GoName}}) {
{{- range .Fields}}
	{{.AppendStmt}}
{{- end}}
}

// AppendSlice appends every element of vs, reserving room for them up front.
func (a *{{.AppenderType}}) AppendSlice(vs []{{.GoName}}) {
	a.rb.Reserve(len(vs))
	for i := range vs {
		a.Append(&vs[i])
	}
}

// NewRecordBatch snapshots the appended rows into a record batch and resets the
// appender for the next batch. The caller owns the batch and must Release it.
func (a *{{.AppenderType}}) NewRecordBatch() arrow.RecordBatch { return a.rb.NewRecordBatch() }

// Err returns the first error an Append hit, or nil. Only dictionary columns
// can fail, so an appender over a schema without one always returns nil.
//
// The error is sticky: NewRecordBatch does not clear it, because a batch built
// after a failed append is missing a value in that column.
func (a *{{.AppenderType}}) Err() error { return a.err }
{{if .AnyFallible}}
// setErr keeps the first error so the hot path stays a single branch.
func (a *{{.AppenderType}}) setErr(err error) {
	if err != nil && a.err == nil {
		a.err = err
	}
}
{{end}}
// Release releases the appender's builders.
func (a *{{.AppenderType}}) Release() { a.rb.Release() }

// {{.BatchFunc}} builds one record batch holding every element of vs. It is the
// generated equivalent of arreflect.RecordFromSlice[{{.GoName}}](vs, mem) and
// produces an identical batch. The caller owns the batch and must Release it.
func {{.BatchFunc}}(mem memory.Allocator, vs []{{.GoName}}) (arrow.RecordBatch, error) {
	a := {{.CtorName}}(mem)
	defer a.Release()
	a.AppendSlice(vs)
	if err := a.Err(); err != nil {
		return nil, err
	}
	return a.NewRecordBatch(), nil
}
{{end}}`))
