// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flatbuf

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type DictionaryEncoding struct {
	flatbuffers.Table
}

func GetRootAsDictionaryEncoding(buf []byte, offset flatbuffers.UOffsetT) *DictionaryEncoding {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &DictionaryEncoding{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *DictionaryEncoding) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv.Bytes = buf
	rcv.Pos = i
}

// / The known dictionary id in the application where this data is used. In
// / the file or streaming formats, the dictionary ids are found in the
// / DictionaryBatch messages
func (rcv *DictionaryEncoding) Id() int64 {
	o := flatbuffers.UOffsetT(rcv.Offset(4))
	if o != 0 {
		return rcv.GetInt64(o + rcv.Pos)
	}
	return 0
}

// / The known dictionary id in the application where this data is used. In
// / the file or streaming formats, the dictionary ids are found in the
// / DictionaryBatch messages
func (rcv *DictionaryEncoding) MutateId(n int64) bool {
	return rcv.MutateInt64Slot(4, n)
}

// / The dictionary indices are constrained to be non-negative integers. If
// / this field is null, the indices must be signed int32. To maximize
// / cross-language compatibility and performance, implementations are
// / recommended to prefer signed integer types over unsigned integer types
// / and to avoid uint64 indices unless they are required by an application.
func (rcv *DictionaryEncoding) IndexType(obj *Int) *Int {
	o := flatbuffers.UOffsetT(rcv.Offset(6))
	if o != 0 {
		x := rcv.Indirect(o + rcv.Pos)
		if obj == nil {
			obj = new(Int)
		}
		obj.Init(rcv.Bytes, x)
		return obj
	}
	return nil
}

// / The dictionary indices are constrained to be non-negative integers. If
// / this field is null, the indices must be signed int32. To maximize
// / cross-language compatibility and performance, implementations are
// / recommended to prefer signed integer types over unsigned integer types
// / and to avoid uint64 indices unless they are required by an application.
// / By default, dictionaries are not ordered, or the order does not have
// / semantic meaning. In some statistical, applications, dictionary-encoding
// / is used to represent ordered categorical data, and we provide a way to
// / preserve that metadata here
func (rcv *DictionaryEncoding) IsOrdered() bool {
	o := flatbuffers.UOffsetT(rcv.Offset(8))
	if o != 0 {
		return rcv.GetBool(o + rcv.Pos)
	}
	return false
}

// / By default, dictionaries are not ordered, or the order does not have
// / semantic meaning. In some statistical, applications, dictionary-encoding
// / is used to represent ordered categorical data, and we provide a way to
// / preserve that metadata here
func (rcv *DictionaryEncoding) MutateIsOrdered(n bool) bool {
	return rcv.MutateBoolSlot(8, n)
}

func (rcv *DictionaryEncoding) DictionaryKind() DictionaryKind {
	o := flatbuffers.UOffsetT(rcv.Offset(10))
	if o != 0 {
		return DictionaryKind(rcv.GetInt16(o + rcv.Pos))
	}
	return 0
}

func (rcv *DictionaryEncoding) MutateDictionaryKind(n DictionaryKind) bool {
	return rcv.MutateInt16Slot(10, int16(n))
}

func DictionaryEncodingStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func DictionaryEncodingAddId(builder *flatbuffers.Builder, id int64) {
	builder.PrependInt64Slot(0, id, 0)
}
func DictionaryEncodingAddIndexType(builder *flatbuffers.Builder, indexType flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(indexType), 0)
}
func DictionaryEncodingAddIsOrdered(builder *flatbuffers.Builder, isOrdered bool) {
	builder.PrependBoolSlot(2, isOrdered, false)
}
func DictionaryEncodingAddDictionaryKind(builder *flatbuffers.Builder, dictionaryKind DictionaryKind) {
	builder.PrependInt16Slot(3, int16(dictionaryKind), 0)
}
func DictionaryEncodingEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
