//go:build go1.18 && amd64 && !noasm && !appengine
// AUTO-GENERATED BY C2GOASM -- DO NOT EDIT

TEXT ·_filter_uint8_avx2(SB), $0-40

	MOVQ values+0(FP), DI
	MOVQ filter+8(FP), SI
	MOVQ output+16(FP), DX
	MOVQ tables+24(FP), CX
	MOVQ length+32(FP), R8

	LONG $0x07408d49         // lea    rax, [r8 + 7]
	WORD $0x854d; BYTE $0xc0 // test    r8, r8
	LONG $0xc0490f49         // cmovns    rax, r8
	LONG $0x08f88349         // cmp    r8, 8
	JL   LBB0_20
	LONG $0x03f8c148         // sar    rax, 3
	WORD $0x3145; BYTE $0xc9 // xor    r9d, r9d
	WORD $0x3145; BYTE $0xc0 // xor    r8d, r8d
	JMP  LBB0_2

LBB0_4:
	LONG $0xc7148b4e // mov    r10, qword [rdi + 8*r8]
	LONG $0x0a14894e // mov    qword [rdx + r9], r10
	LONG $0x08c18349 // add    r9, 8

LBB0_19:
	WORD $0xff49; BYTE $0xc0 // inc    r8
	WORD $0x394c; BYTE $0xc0 // cmp    rax, r8
	JE   LBB0_20

LBB0_2:
	LONG $0x1cb60f46; BYTE $0x06               // movzx    r11d, byte [rsi + r8]
	WORD $0x854d; BYTE $0xdb                   // test    r11, r11
	JE   LBB0_19
	LONG $0xfffb8141; WORD $0x0000; BYTE $0x00 // cmp    r11d, 255
	JE   LBB0_4
	QUAD $0x0010001994b60f46; BYTE $0x00       // movzx    r10d, byte [rcx + r11 + 4096]
	LONG $0x04e3c141                           // shl    r11d, 4
	LONG $0x7e7aa1c4; WORD $0xc704             // vmovq    xmm0, qword [rdi + 8*r8]
	LONG $0x0079a2c4; WORD $0x1904             // vpshufb    xmm0, xmm0, oword [rcx + r11]
	LONG $0x04fa8349                           // cmp    r10, 4
	JB   LBB0_13
	LONG $0x7e79a1c4; WORD $0x0a04             // vmovd    dword [rdx + r9], xmm0
	LONG $0x04598d4d                           // lea    r11, [r9 + 4]
	LONG $0x07fa8041                           // cmp    r10b, 7
	JB   LBB0_8
	QUAD $0x06060a441479a3c4                   // vpextrb    byte [rdx + r9 + 6], xmm0, 6
	JMP  LBB0_10

LBB0_13:
	WORD $0x854d; BYTE $0xd2                   // test    r10, r10
	JE   LBB0_19
	LONG $0x1479a3c4; WORD $0x0a04; BYTE $0x00 // vpextrb    byte [rdx + r9], xmm0, 0
	LONG $0x01fa8341                           // cmp    r10d, 1
	JNE  LBB0_16
	WORD $0xff49; BYTE $0xc1                   // inc    r9
	JMP  LBB0_19

LBB0_8:
	LONG $0x04fa8349 // cmp    r10, 4
	JE   LBB0_12
	LONG $0x06fa8341 // cmp    r10d, 6
	JNE  LBB0_11

LBB0_10:
	QUAD $0x05050a441479a3c4 // vpextrb    byte [rdx + r9 + 5], xmm0, 5

LBB0_11:
	LONG $0x1479a3c4; WORD $0x1a04; BYTE $0x04 // vpextrb    byte [rdx + r11], xmm0, 4

LBB0_12:
	LONG $0xfcc28341         // add    r10d, -4
	WORD $0x014d; BYTE $0xd3 // add    r11, r10
	WORD $0x894d; BYTE $0xd9 // mov    r9, r11
	JMP  LBB0_19

LBB0_16:
	QUAD $0x01010a441479a3c4 // vpextrb    byte [rdx + r9 + 1], xmm0, 1
	LONG $0x02fa8341         // cmp    r10d, 2
	JNE  LBB0_18
	LONG $0x02c18349         // add    r9, 2
	JMP  LBB0_19

LBB0_18:
	QUAD $0x02020a441479a3c4 // vpextrb    byte [rdx + r9 + 2], xmm0, 2
	LONG $0x03c18349         // add    r9, 3
	JMP  LBB0_19

LBB0_20:
	RET
