//+build !noasm !appengine
// AUTO-GENERATED BY C2GOASM -- DO NOT EDIT

TEXT ·_filter_uint64_avx2(SB), $0-40

	MOVQ values+0(FP), DI
	MOVQ filter+8(FP), SI
	MOVQ output+16(FP), DX
	MOVQ tables+24(FP), CX
	MOVQ length+32(FP), R8

	LONG $0x07408d49         // lea    rax, [r8 + 7]
	WORD $0x854d; BYTE $0xc0 // test    r8, r8
	LONG $0xc0490f49         // cmovns    rax, r8
	LONG $0x08f88349         // cmp    r8, 8
	JL   LBB0_11
	WORD $0x5641             // push    r14
	BYTE $0x53               // push    rbx
	LONG $0x03f8c148         // sar    rax, 3
	LONG $0x20c78348         // add    rdi, 32
	WORD $0x3145; BYTE $0xc0 // xor    r8d, r8d
	WORD $0x3145; BYTE $0xc9 // xor    r9d, r9d
	JMP  LBB0_2

LBB0_4:
	LONG $0x476ffec5; BYTE $0xe0               // vmovdqu    ymm0, yword [rdi - 32]
	LONG $0x0f6ffec5                           // vmovdqu    ymm1, yword [rdi]
	LONG $0x7f7ea1c4; WORD $0xc204             // vmovdqu    yword [rdx + 8*r8], ymm0
	LONG $0x7f7ea1c4; WORD $0xc24c; BYTE $0x20 // vmovdqu    yword [rdx + 8*r8 + 32], ymm1
	LONG $0x08c08349                           // add    r8, 8

LBB0_9:
	WORD $0xff49; BYTE $0xc1 // inc    r9
	LONG $0x40c78348         // add    rdi, 64
	WORD $0x394c; BYTE $0xc8 // cmp    rax, r9
	JE   LBB0_10

LBB0_2:
	LONG $0x14b60f46; BYTE $0x0e               // movzx    r10d, byte [rsi + r9]
	WORD $0x8545; BYTE $0xd2                   // test    r10d, r10d
	JE   LBB0_9
	LONG $0xfffa8141; WORD $0x0000; BYTE $0x00 // cmp    r10d, 255
	JE   LBB0_4
	WORD $0x8945; BYTE $0xd6                   // mov    r14d, r10d
	LONG $0x0fe68341                           // and    r14d, 15
	LONG $0x04eac141                           // shr    r10d, 4
	QUAD $0x0002a0319cb60f42; BYTE $0x00       // movzx    ebx, byte [rcx + r14 + 672]
	QUAD $0x0002a0119cb60f46; BYTE $0x00       // movzx    r11d, byte [rcx + r10 + 672]
	WORD $0x8548; BYTE $0xdb                   // test    rbx, rbx
	JE   LBB0_7
	LONG $0x05e6c141                           // shl    r14d, 5
	LONG $0x6f7ea1c4; WORD $0x3104             // vmovdqu    ymm0, yword [rcx + r14]
	LONG $0x367de2c4; WORD $0xe047             // vpermd    ymm0, ymm0, yword [rdi - 32]
	WORD $0x8941; BYTE $0xde                   // mov    r14d, ebx
	LONG $0x05e6c141                           // shl    r14d, 5
	QUAD $0x0200318c6f7ea1c4; WORD $0x0000     // vmovdqu    ymm1, yword [rcx + r14 + 512]
	LONG $0x8e75a2c4; WORD $0xc204             // vpmaskmovd    yword [rdx + 8*r8], ymm1, ymm0
	WORD $0x0149; BYTE $0xd8                   // add    r8, rbx

LBB0_7:
	WORD $0x854d; BYTE $0xdb               // test    r11, r11
	JE   LBB0_9
	LONG $0x05e2c141                       // shl    r10d, 5
	LONG $0x6f7ea1c4; WORD $0x1104         // vmovdqu    ymm0, yword [rcx + r10]
	LONG $0x367de2c4; BYTE $0x07           // vpermd    ymm0, ymm0, yword [rdi]
	WORD $0x8945; BYTE $0xda               // mov    r10d, r11d
	LONG $0x05e2c141                       // shl    r10d, 5
	QUAD $0x0200118c6f7ea1c4; WORD $0x0000 // vmovdqu    ymm1, yword [rcx + r10 + 512]
	LONG $0x8e75a2c4; WORD $0xc204         // vpmaskmovd    yword [rdx + 8*r8], ymm1, ymm0
	WORD $0x014d; BYTE $0xd8               // add    r8, r11
	JMP  LBB0_9

LBB0_10:
	BYTE $0x5b   // pop    rbx
	WORD $0x5e41 // pop    r14

LBB0_11:
	VZEROUPPER
	RET
