//go:build go1.18 && amd64 && !noasm && !appengine
// AUTO-GENERATED BY C2GOASM -- DO NOT EDIT

TEXT ·_filter_uint16_avx2(SB), $0-40

	MOVQ values+0(FP), DI
	MOVQ filter+8(FP), SI
	MOVQ output+16(FP), DX
	MOVQ tables+24(FP), CX
	MOVQ length+32(FP), R8

	LONG $0x07408d49         // lea    rax, [r8 + 7]
	WORD $0x854d; BYTE $0xc0 // test    r8, r8
	LONG $0xc0490f49         // cmovns    rax, r8
	LONG $0x08f88349         // cmp    r8, 8
	JL   LBB0_21
	LONG $0x03f8c148         // sar    rax, 3
	WORD $0x3145; BYTE $0xc0 // xor    r8d, r8d
	WORD $0x3145; BYTE $0xc9 // xor    r9d, r9d
	JMP  LBB0_2

LBB0_4:
	LONG $0x076ffac5               // vmovdqu    xmm0, oword [rdi]
	LONG $0x7f7aa1c4; WORD $0x4204 // vmovdqu    oword [rdx + 2*r8], xmm0
	LONG $0x08c08349               // add    r8, 8

LBB0_20:
	WORD $0xff49; BYTE $0xc1 // inc    r9
	LONG $0x10c78348         // add    rdi, 16
	WORD $0x394c; BYTE $0xc8 // cmp    rax, r9
	JE   LBB0_21

LBB0_2:
	LONG $0x1cb60f46; BYTE $0x0e               // movzx    r11d, byte [rsi + r9]
	WORD $0x8545; BYTE $0xdb                   // test    r11d, r11d
	JE   LBB0_20
	LONG $0xfffb8141; WORD $0x0000; BYTE $0x00 // cmp    r11d, 255
	JE   LBB0_4
	QUAD $0x0010001994b60f46; BYTE $0x00       // movzx    r10d, byte [rcx + r11 + 4096]
	LONG $0x04e3c141                           // shl    r11d, 4
	LONG $0x076ffac5                           // vmovdqu    xmm0, oword [rdi]
	LONG $0x0079a2c4; WORD $0x1904             // vpshufb    xmm0, xmm0, oword [rcx + r11]
	LONG $0x04fa8349                           // cmp    r10, 4
	JB   LBB0_13
	LONG $0xd679a1c4; WORD $0x4204             // vmovq    qword [rdx + 2*r8], xmm0
	LONG $0x07fa8041                           // cmp    r10b, 7
	JB   LBB0_8
	QUAD $0x060c42441579a3c4                   // vpextrw    word [rdx + 2*r8 + 12], xmm0, 6
	JMP  LBB0_10

LBB0_13:
	LONG $0x03fa8341         // cmp    r10d, 3
	JNE  LBB0_15
	QUAD $0x020442441579a3c4 // vpextrw    word [rdx + 2*r8 + 4], xmm0, 2
	QUAD $0x010242441579a3c4 // vpextrw    word [rdx + 2*r8 + 2], xmm0, 1
	JMP  LBB0_18

LBB0_8:
	LONG $0x04fa8349 // cmp    r10, 4
	JE   LBB0_12
	LONG $0x06fa8341 // cmp    r10d, 6
	JNE  LBB0_11

LBB0_10:
	QUAD $0x050a42441579a3c4 // vpextrw    word [rdx + 2*r8 + 10], xmm0, 5

LBB0_11:
	QUAD $0x040842441579a3c4 // vpextrw    word [rdx + 2*r8 + 8], xmm0, 4

LBB0_12:
	LONG $0x04c08349 // add    r8, 4
	LONG $0xfcc28341 // add    r10d, -4
	JMP  LBB0_19

LBB0_15:
	LONG $0x02fa8041         // cmp    r10b, 2
	JB   LBB0_17
	QUAD $0x010242441579a3c4 // vpextrw    word [rdx + 2*r8 + 2], xmm0, 1
	JMP  LBB0_18

LBB0_17:
	WORD $0x854d; BYTE $0xd2 // test    r10, r10
	JE   LBB0_19

LBB0_18:
	LONG $0x1579a3c4; WORD $0x4204; BYTE $0x00 // vpextrw    word [rdx + 2*r8], xmm0, 0

LBB0_19:
	WORD $0x014d; BYTE $0xd0 // add    r8, r10
	JMP  LBB0_20

LBB0_21:
	RET
