//go:build go1.18 && amd64 && !noasm && !appengine
// AUTO-GENERATED BY C2GOASM -- DO NOT EDIT

DATA LCDATA1<>+0x000(SB)/8, $0x0000000100000000
DATA LCDATA1<>+0x008(SB)/8, $0x0000000300000002
DATA LCDATA1<>+0x010(SB)/8, $0x0000000500000004
DATA LCDATA1<>+0x018(SB)/8, $0x0000000700000006
DATA LCDATA1<>+0x020(SB)/8, $0x0000000000000008
GLOBL LCDATA1<>(SB), 8, $40

TEXT ·_get_take_indices_uint32_avx2(SB), $0-40

	MOVQ filter+0(FP), DI
	MOVQ output+8(FP), SI
	MOVQ tables+16(FP), DX
	MOVQ nbytes+24(FP), CX
	MOVQ tailMask+32(FP), R8
	LEAQ LCDATA1<>(SB), BP

	WORD $0x8548; BYTE $0xc9       // test    rcx, rcx
	JLE  LBB0_10
	WORD $0xff48; BYTE $0xc9       // dec    rcx
	JE   LBB0_2
	LONG $0xc0eff9c5               // vpxor    xmm0, xmm0, xmm0
	LONG $0x5879e2c4; WORD $0x204d // vpbroadcastd    xmm1, dword 32[rbp] /* [rip + .LCPI0_2] */
	WORD $0xc031                   // xor    eax, eax
	LONG $0x556ff9c5; BYTE $0x00   // vmovdqa    xmm2, oword 0[rbp] /* [rip + .LCPI0_0] */
	LONG $0x5d6ff9c5; BYTE $0x10   // vmovdqa    xmm3, oword 16[rbp] /* [rip + .LCPI0_1] */
	WORD $0x3145; BYTE $0xc9       // xor    r9d, r9d
	JMP  LBB0_12

LBB0_14:
	LONG $0xe2ebf9c5               // vpor    xmm4, xmm0, xmm2
	LONG $0xebebf9c5               // vpor    xmm5, xmm0, xmm3
	LONG $0x247ffac5; BYTE $0x86   // vmovdqu    oword [rsi + 4*rax], xmm4
	LONG $0x6c7ffac5; WORD $0x1086 // vmovdqu    oword [rsi + 4*rax + 16], xmm5
	LONG $0x08c08348               // add    rax, 8

LBB0_19:
	LONG $0xc1fef9c5         // vpaddd    xmm0, xmm0, xmm1
	WORD $0xff49; BYTE $0xc1 // inc    r9
	WORD $0x394c; BYTE $0xc9 // cmp    rcx, r9
	JE   LBB0_3

LBB0_12:
	LONG $0x14b60f46; BYTE $0x0f               // movzx    r10d, byte [rdi + r9]
	WORD $0x8545; BYTE $0xd2                   // test    r10d, r10d
	JE   LBB0_19
	LONG $0xfffa8141; WORD $0x0000; BYTE $0x00 // cmp    r10d, 255
	JE   LBB0_14
	WORD $0x8945; BYTE $0xd3                   // mov    r11d, r10d
	LONG $0x0fe38341                           // and    r11d, 15
	WORD $0x8945; BYTE $0xd6                   // mov    r14d, r10d
	LONG $0x04eec141                           // shr    r14d, 4
	QUAD $0x0001501a9cb60f42; BYTE $0x00       // movzx    ebx, byte [rdx + r11 + 336]
	QUAD $0x000150329cb60f46; BYTE $0x00       // movzx    r11d, byte [rdx + r14 + 336]
	WORD $0x8548; BYTE $0xdb                   // test    rbx, rbx
	JE   LBB0_17
	WORD $0x8945; BYTE $0xd6                   // mov    r14d, r10d
	LONG $0x04e6c041                           // shl    r14b, 4
	LONG $0xf6b60f45                           // movzx    r14d, r14b
	LONG $0xe2ebf9c5                           // vpor    xmm4, xmm0, xmm2
	LONG $0x0059a2c4; WORD $0x3224             // vpshufb    xmm4, xmm4, oword [rdx + r14]
	WORD $0x8941; BYTE $0xde                   // mov    r14d, ebx
	LONG $0x04e6c141                           // shl    r14d, 4
	QUAD $0x010032ac6f7aa1c4; WORD $0x0000     // vmovdqu    xmm5, oword [rdx + r14 + 256]
	LONG $0x8e51e2c4; WORD $0x8624             // vpmaskmovd    oword [rsi + 4*rax], xmm5, xmm4
	WORD $0x0148; BYTE $0xd8                   // add    rax, rbx

LBB0_17:
	WORD $0x854d; BYTE $0xdb               // test    r11, r11
	JE   LBB0_19
	LONG $0xf0e28341                       // and    r10d, -16
	LONG $0xe3ebf9c5                       // vpor    xmm4, xmm0, xmm3
	LONG $0x0059a2c4; WORD $0x1224         // vpshufb    xmm4, xmm4, oword [rdx + r10]
	WORD $0x8945; BYTE $0xda               // mov    r10d, r11d
	LONG $0x04e2c141                       // shl    r10d, 4
	QUAD $0x010012ac6f7aa1c4; WORD $0x0000 // vmovdqu    xmm5, oword [rdx + r10 + 256]
	LONG $0x8e51e2c4; WORD $0x8624         // vpmaskmovd    oword [rsi + 4*rax], xmm5, xmm4
	WORD $0x014c; BYTE $0xd8               // add    rax, r11
	JMP  LBB0_19

LBB0_2:
	WORD $0xc031             // xor    eax, eax
	LONG $0xc0eff9c5         // vpxor    xmm0, xmm0, xmm0
	WORD $0x3145; BYTE $0xc9 // xor    r9d, r9d

LBB0_3:
	LONG $0x3cb60f42; BYTE $0x0f               // movzx    edi, byte [rdi + r9]
	WORD $0x3949; BYTE $0xc9                   // cmp    r9, rcx
	LONG $0xc8b60f41                           // movzx    ecx, r8b
	LONG $0x00ffb841; WORD $0x0000             // mov    r8d, 255
	LONG $0xc1440f44                           // cmove    r8d, ecx
	WORD $0x2141; BYTE $0xf8                   // and    r8d, edi
	JE   LBB0_10
	LONG $0xfff88141; WORD $0x0000; BYTE $0x00 // cmp    r8d, 255
	JNE  LBB0_6
	LONG $0x4debf9c5; BYTE $0x00               // vpor    xmm1, xmm0, oword 0[rbp] /* [rip + .LCPI0_0] */
	LONG $0x45ebf9c5; BYTE $0x10               // vpor    xmm0, xmm0, oword 16[rbp] /* [rip + .LCPI0_1] */
	LONG $0x0c7ffac5; BYTE $0x86               // vmovdqu    oword [rsi + 4*rax], xmm1
	LONG $0x447ffac5; WORD $0x1086             // vmovdqu    oword [rsi + 4*rax + 16], xmm0
	JMP  LBB0_10

LBB0_6:
	WORD $0x8944; BYTE $0xc7               // mov    edi, r8d
	WORD $0xe783; BYTE $0x0f               // and    edi, 15
	LONG $0xc8b60f41                       // movzx    ecx, r8b
	WORD $0x8941; BYTE $0xca               // mov    r10d, ecx
	LONG $0x04eac141                       // shr    r10d, 4
	QUAD $0x0001503a8cb60f44; BYTE $0x00   // movzx    r9d, byte [rdx + rdi + 336]
	QUAD $0x00015012bcb60f42; BYTE $0x00   // movzx    edi, byte [rdx + r10 + 336]
	WORD $0x854d; BYTE $0xc9               // test    r9, r9
	JE   LBB0_8
	LONG $0x04e0c041                       // shl    r8b, 4
	LONG $0xc0b60f45                       // movzx    r8d, r8b
	LONG $0x4debf9c5; BYTE $0x00           // vpor    xmm1, xmm0, oword 0[rbp] /* [rip + .LCPI0_0] */
	LONG $0x0071a2c4; WORD $0x020c         // vpshufb    xmm1, xmm1, oword [rdx + r8]
	WORD $0x8945; BYTE $0xc8               // mov    r8d, r9d
	LONG $0x04e0c141                       // shl    r8d, 4
	QUAD $0x010002946f7aa1c4; WORD $0x0000 // vmovdqu    xmm2, oword [rdx + r8 + 256]
	LONG $0x8e69e2c4; WORD $0x860c         // vpmaskmovd    oword [rsi + 4*rax], xmm2, xmm1
	WORD $0x014c; BYTE $0xc8               // add    rax, r9

LBB0_8:
	WORD $0x8548; BYTE $0xff             // test    rdi, rdi
	JE   LBB0_10
	LONG $0x00f0e181; WORD $0x0000       // and    ecx, 240
	LONG $0x45ebf9c5; BYTE $0x10         // vpor    xmm0, xmm0, oword 16[rbp] /* [rip + .LCPI0_1] */
	LONG $0x0079e2c4; WORD $0x0a04       // vpshufb    xmm0, xmm0, oword [rdx + rcx]
	WORD $0xe7c1; BYTE $0x04             // shl    edi, 4
	QUAD $0x0001003a8c6ffac5; BYTE $0x00 // vmovdqu    xmm1, oword [rdx + rdi + 256]
	LONG $0x8e71e2c4; WORD $0x8604       // vpmaskmovd    oword [rsi + 4*rax], xmm1, xmm0

LBB0_10:
	RET
