// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by arrgen. DO NOT EDIT.

package gentypes

import (
	"time"

	"github.com/apache/arrow-go/v18/arrow"
	"github.com/apache/arrow-go/v18/arrow/array"
	"github.com/apache/arrow-go/v18/arrow/memory"
)

// rowArrowSchema is the Arrow schema of Row, resolved from its arrow
// struct tags.
var rowArrowSchema = arrow.NewSchema([]arrow.Field{
	{Name: "b", Type: arrow.FixedWidthTypes.Boolean, Nullable: false},
	{Name: "i8", Type: arrow.PrimitiveTypes.Int8, Nullable: false},
	{Name: "i16", Type: arrow.PrimitiveTypes.Int16, Nullable: false},
	{Name: "i32", Type: arrow.PrimitiveTypes.Int32, Nullable: false},
	{Name: "i64", Type: arrow.PrimitiveTypes.Int64, Nullable: false},
	{Name: "i", Type: arrow.PrimitiveTypes.Int64, Nullable: false},
	{Name: "u8", Type: arrow.PrimitiveTypes.Uint8, Nullable: false},
	{Name: "u16", Type: arrow.PrimitiveTypes.Uint16, Nullable: false},
	{Name: "u32", Type: arrow.PrimitiveTypes.Uint32, Nullable: false},
	{Name: "u64", Type: arrow.PrimitiveTypes.Uint64, Nullable: false},
	{Name: "u", Type: arrow.PrimitiveTypes.Uint64, Nullable: false},
	{Name: "f32", Type: arrow.PrimitiveTypes.Float32, Nullable: false},
	{Name: "f64", Type: arrow.PrimitiveTypes.Float64, Nullable: false},
	{Name: "s", Type: arrow.BinaryTypes.String, Nullable: false},
	{Name: "bin", Type: arrow.BinaryTypes.Binary, Nullable: false},
	{Name: "ts", Type: &arrow.TimestampType{Unit: arrow.Nanosecond, TimeZone: "UTC"}, Nullable: false},
	{Name: "d32", Type: arrow.FixedWidthTypes.Date32, Nullable: false},
	{Name: "d64", Type: arrow.FixedWidthTypes.Date64, Nullable: false},
	{Name: "t32", Type: &arrow.Time32Type{Unit: arrow.Millisecond}, Nullable: false},
	{Name: "t64", Type: &arrow.Time64Type{Unit: arrow.Nanosecond}, Nullable: false},
	{Name: "dur", Type: &arrow.DurationType{Unit: arrow.Nanosecond}, Nullable: false},
	{Name: "dec32", Type: &arrow.Decimal32Type{Precision: 9, Scale: 0}, Nullable: false},
	{Name: "dec64", Type: &arrow.Decimal64Type{Precision: 18, Scale: 4}, Nullable: false},
	{Name: "dec128", Type: &arrow.Decimal128Type{Precision: 20, Scale: 3}, Nullable: false},
	{Name: "dec256", Type: &arrow.Decimal256Type{Precision: 76, Scale: 0}, Nullable: false},
	{Name: "ls", Type: arrow.BinaryTypes.LargeString, Nullable: false},
	{Name: "vs", Type: arrow.BinaryTypes.StringView, Nullable: false},
	{Name: "lb", Type: arrow.BinaryTypes.LargeBinary, Nullable: false},
	{Name: "vb", Type: arrow.BinaryTypes.BinaryView, Nullable: false},
	{Name: "ds", Type: &arrow.DictionaryType{IndexType: arrow.PrimitiveTypes.Int32, ValueType: arrow.BinaryTypes.String}, Nullable: false},
	{Name: "db", Type: &arrow.DictionaryType{IndexType: arrow.PrimitiveTypes.Int32, ValueType: arrow.BinaryTypes.Binary}, Nullable: false},
	{Name: "di", Type: &arrow.DictionaryType{IndexType: arrow.PrimitiveTypes.Int32, ValueType: arrow.PrimitiveTypes.Int32}, Nullable: false},
	{Name: "df", Type: &arrow.DictionaryType{IndexType: arrow.PrimitiveTypes.Int32, ValueType: arrow.PrimitiveTypes.Float64}, Nullable: false},
	{Name: "Untagged", Type: arrow.PrimitiveTypes.Int64, Nullable: false},
	{Name: "pb", Type: arrow.FixedWidthTypes.Boolean, Nullable: true},
	{Name: "pi64", Type: arrow.PrimitiveTypes.Int64, Nullable: true},
	{Name: "pf64", Type: arrow.PrimitiveTypes.Float64, Nullable: true},
	{Name: "ps", Type: arrow.BinaryTypes.String, Nullable: true},
	{Name: "pbin", Type: arrow.BinaryTypes.Binary, Nullable: true},
	{Name: "pts", Type: &arrow.TimestampType{Unit: arrow.Nanosecond, TimeZone: "UTC"}, Nullable: true},
	{Name: "pd32", Type: arrow.FixedWidthTypes.Date32, Nullable: true},
	{Name: "pt64", Type: &arrow.Time64Type{Unit: arrow.Nanosecond}, Nullable: true},
	{Name: "pdur", Type: &arrow.DurationType{Unit: arrow.Nanosecond}, Nullable: true},
	{Name: "pdec32", Type: &arrow.Decimal32Type{Precision: 9, Scale: 0}, Nullable: true},
	{Name: "pdec128", Type: &arrow.Decimal128Type{Precision: 38, Scale: 0}, Nullable: true},
	{Name: "pds", Type: &arrow.DictionaryType{IndexType: arrow.PrimitiveTypes.Int32, ValueType: arrow.BinaryTypes.String}, Nullable: true},
}, nil)

// RowSchema returns the Arrow schema encoded by RowAppender.
func RowSchema() *arrow.Schema { return rowArrowSchema }

// RowAppender converts Row values into Arrow record batches
// without reflection.
//
// It is not safe for concurrent use. Release it when done.
type RowAppender struct {
	rb  *array.RecordBuilder
	b0  *array.BooleanBuilder
	b1  *array.Int8Builder
	b2  *array.Int16Builder
	b3  *array.Int32Builder
	b4  *array.Int64Builder
	b5  *array.Int64Builder
	b6  *array.Uint8Builder
	b7  *array.Uint16Builder
	b8  *array.Uint32Builder
	b9  *array.Uint64Builder
	b10 *array.Uint64Builder
	b11 *array.Float32Builder
	b12 *array.Float64Builder
	b13 *array.StringBuilder
	b14 *array.BinaryBuilder
	b15 *array.TimestampBuilder
	b16 *array.Date32Builder
	b17 *array.Date64Builder
	b18 *array.Time32Builder
	b19 *array.Time64Builder
	b20 *array.DurationBuilder
	b21 *array.Decimal32Builder
	b22 *array.Decimal64Builder
	b23 *array.Decimal128Builder
	b24 *array.Decimal256Builder
	b25 *array.LargeStringBuilder
	b26 *array.StringViewBuilder
	b27 *array.BinaryBuilder
	b28 *array.BinaryViewBuilder
	b29 *array.BinaryDictionaryBuilder
	b30 *array.BinaryDictionaryBuilder
	b31 *array.Int32DictionaryBuilder
	b32 *array.Float64DictionaryBuilder
	b33 *array.Int64Builder
	b34 *array.BooleanBuilder
	b35 *array.Int64Builder
	b36 *array.Float64Builder
	b37 *array.StringBuilder
	b38 *array.BinaryBuilder
	b39 *array.TimestampBuilder
	b40 *array.Date32Builder
	b41 *array.Time64Builder
	b42 *array.DurationBuilder
	b43 *array.Decimal32Builder
	b44 *array.Decimal128Builder
	b45 *array.BinaryDictionaryBuilder
	err error
}

// NewRowAppender returns an appender that builds Row batches with mem,
// or memory.DefaultAllocator when mem is nil. The typed field builders are
// resolved once here, so Append does no type assertions.
func NewRowAppender(mem memory.Allocator) *RowAppender {
	if mem == nil {
		mem = memory.DefaultAllocator
	}
	rb := array.NewRecordBuilder(mem, rowArrowSchema)
	return &RowAppender{
		rb:  rb,
		b0:  rb.Field(0).(*array.BooleanBuilder),
		b1:  rb.Field(1).(*array.Int8Builder),
		b2:  rb.Field(2).(*array.Int16Builder),
		b3:  rb.Field(3).(*array.Int32Builder),
		b4:  rb.Field(4).(*array.Int64Builder),
		b5:  rb.Field(5).(*array.Int64Builder),
		b6:  rb.Field(6).(*array.Uint8Builder),
		b7:  rb.Field(7).(*array.Uint16Builder),
		b8:  rb.Field(8).(*array.Uint32Builder),
		b9:  rb.Field(9).(*array.Uint64Builder),
		b10: rb.Field(10).(*array.Uint64Builder),
		b11: rb.Field(11).(*array.Float32Builder),
		b12: rb.Field(12).(*array.Float64Builder),
		b13: rb.Field(13).(*array.StringBuilder),
		b14: rb.Field(14).(*array.BinaryBuilder),
		b15: rb.Field(15).(*array.TimestampBuilder),
		b16: rb.Field(16).(*array.Date32Builder),
		b17: rb.Field(17).(*array.Date64Builder),
		b18: rb.Field(18).(*array.Time32Builder),
		b19: rb.Field(19).(*array.Time64Builder),
		b20: rb.Field(20).(*array.DurationBuilder),
		b21: rb.Field(21).(*array.Decimal32Builder),
		b22: rb.Field(22).(*array.Decimal64Builder),
		b23: rb.Field(23).(*array.Decimal128Builder),
		b24: rb.Field(24).(*array.Decimal256Builder),
		b25: rb.Field(25).(*array.LargeStringBuilder),
		b26: rb.Field(26).(*array.StringViewBuilder),
		b27: rb.Field(27).(*array.BinaryBuilder),
		b28: rb.Field(28).(*array.BinaryViewBuilder),
		b29: rb.Field(29).(*array.BinaryDictionaryBuilder),
		b30: rb.Field(30).(*array.BinaryDictionaryBuilder),
		b31: rb.Field(31).(*array.Int32DictionaryBuilder),
		b32: rb.Field(32).(*array.Float64DictionaryBuilder),
		b33: rb.Field(33).(*array.Int64Builder),
		b34: rb.Field(34).(*array.BooleanBuilder),
		b35: rb.Field(35).(*array.Int64Builder),
		b36: rb.Field(36).(*array.Float64Builder),
		b37: rb.Field(37).(*array.StringBuilder),
		b38: rb.Field(38).(*array.BinaryBuilder),
		b39: rb.Field(39).(*array.TimestampBuilder),
		b40: rb.Field(40).(*array.Date32Builder),
		b41: rb.Field(41).(*array.Time64Builder),
		b42: rb.Field(42).(*array.DurationBuilder),
		b43: rb.Field(43).(*array.Decimal32Builder),
		b44: rb.Field(44).(*array.Decimal128Builder),
		b45: rb.Field(45).(*array.BinaryDictionaryBuilder),
	}
}

// Schema returns the schema of the batches this appender builds.
func (a *RowAppender) Schema() *arrow.Schema { return rowArrowSchema }

// RecordBuilder returns the underlying builder. Appending through it directly
// is allowed as long as every column stays the same length.
func (a *RowAppender) RecordBuilder() *array.RecordBuilder { return a.rb }

// Reserve pre-allocates room for n more rows in every column. Reserving before
// a run of Appends keeps the append path free of allocations.
func (a *RowAppender) Reserve(n int) { a.rb.Reserve(n) }

// Len reports the number of rows appended since the last NewRecordBatch.
func (a *RowAppender) Len() int { return a.rb.Field(0).Len() }

// Append appends one row. v is read synchronously and never retained, so a
// caller can reuse a single Row variable across calls.
func (a *RowAppender) Append(v *Row) {
	a.b0.Append(v.Bool)
	a.b1.Append(v.Int8)
	a.b2.Append(v.Int16)
	a.b3.Append(v.Int32)
	a.b4.Append(v.Int64)
	a.b5.Append(int64(v.Int))
	a.b6.Append(v.Uint8)
	a.b7.Append(v.Uint16)
	a.b8.Append(v.Uint32)
	a.b9.Append(v.Uint64)
	a.b10.Append(uint64(v.Uint))
	a.b11.Append(v.Float32)
	a.b12.Append(v.Float64)
	a.b13.Append(v.Str)
	if v.Bin == nil {
		a.b14.AppendNull()
	} else {
		a.b14.Append(v.Bin)
	}
	a.b15.Append(arrow.Timestamp(v.Timestamp.UnixNano()))
	a.b16.Append(arrow.Date32FromTime(v.Date32))
	a.b17.Append(arrow.Date64FromTime(v.Date64))
	{
		tod := v.Time32.UTC()
		a.b18.Append(arrow.Time32(tod.Sub(time.Date(tod.Year(), tod.Month(), tod.Day(), 0, 0, 0, 0, time.UTC)).Nanoseconds() / 1e6))
	}
	{
		tod := v.Time64.UTC()
		a.b19.Append(arrow.Time64(tod.Sub(time.Date(tod.Year(), tod.Month(), tod.Day(), 0, 0, 0, 0, time.UTC)).Nanoseconds()))
	}
	a.b20.Append(arrow.Duration(v.Duration.Nanoseconds()))
	a.b21.Append(v.Dec32)
	a.b22.Append(v.Dec64)
	a.b23.Append(v.Dec128)
	a.b24.Append(v.Dec256)
	a.b25.Append(v.LargeStr)
	a.b26.Append(v.ViewStr)
	if v.LargeBin == nil {
		a.b27.AppendNull()
	} else {
		a.b27.Append(v.LargeBin)
	}
	if v.ViewBin == nil {
		a.b28.AppendNull()
	} else {
		a.b28.Append(v.ViewBin)
	}
	a.setErr(a.b29.AppendString(v.DictStr))
	if v.DictBin == nil {
		a.b30.AppendNull()
	} else {
		a.setErr(a.b30.Append(v.DictBin))
	}
	a.setErr(a.b31.Append(v.DictInt))
	a.setErr(a.b32.Append(v.DictF64))
	a.b33.Append(v.Untagged)
	if v.PBool == nil {
		a.b34.AppendNull()
	} else {
		a.b34.Append(*v.PBool)
	}
	if v.PInt64 == nil {
		a.b35.AppendNull()
	} else {
		a.b35.Append(*v.PInt64)
	}
	if v.PF64 == nil {
		a.b36.AppendNull()
	} else {
		a.b36.Append(*v.PF64)
	}
	if v.PStr == nil {
		a.b37.AppendNull()
	} else {
		a.b37.Append(*v.PStr)
	}
	if v.PBin == nil || *v.PBin == nil {
		a.b38.AppendNull()
	} else {
		a.b38.Append(*v.PBin)
	}
	if v.PTS == nil {
		a.b39.AppendNull()
	} else {
		a.b39.Append(arrow.Timestamp((*v.PTS).UnixNano()))
	}
	if v.PDate32 == nil {
		a.b40.AppendNull()
	} else {
		a.b40.Append(arrow.Date32FromTime(*v.PDate32))
	}
	if v.PTime64 == nil {
		a.b41.AppendNull()
	} else {
		tod := (*v.PTime64).UTC()
		a.b41.Append(arrow.Time64(tod.Sub(time.Date(tod.Year(), tod.Month(), tod.Day(), 0, 0, 0, 0, time.UTC)).Nanoseconds()))
	}
	if v.PDur == nil {
		a.b42.AppendNull()
	} else {
		a.b42.Append(arrow.Duration((*v.PDur).Nanoseconds()))
	}
	if v.PDec32 == nil {
		a.b43.AppendNull()
	} else {
		a.b43.Append(*v.PDec32)
	}
	if v.PDec128 == nil {
		a.b44.AppendNull()
	} else {
		a.b44.Append(*v.PDec128)
	}
	if v.PDictS == nil {
		a.b45.AppendNull()
	} else {
		a.setErr(a.b45.AppendString(*v.PDictS))
	}
}

// AppendSlice appends every element of vs, reserving room for them up front.
func (a *RowAppender) AppendSlice(vs []Row) {
	a.rb.Reserve(len(vs))
	for i := range vs {
		a.Append(&vs[i])
	}
}

// NewRecordBatch returns the appended rows as a record batch and resets the
// appender. The caller must Release the batch.
func (a *RowAppender) NewRecordBatch() arrow.RecordBatch { return a.rb.NewRecordBatch() }

// Err returns the first error an Append hit, or nil. Only dictionary columns
// can fail. The error is sticky: NewRecordBatch does not clear it.
func (a *RowAppender) Err() error { return a.err }

// setErr keeps the first error.
func (a *RowAppender) setErr(err error) {
	if err != nil && a.err == nil {
		a.err = err
	}
}

// Release releases the appender's builders.
func (a *RowAppender) Release() { a.rb.Release() }

// RowRecordBatch builds one record batch holding every element of vs. It is the
// generated equivalent of arreflect.RecordFromSlice[Row](vs, mem). The
// caller must Release the batch.
func RowRecordBatch(mem memory.Allocator, vs []Row) (arrow.RecordBatch, error) {
	a := NewRowAppender(mem)
	defer a.Release()
	a.AppendSlice(vs)
	if err := a.Err(); err != nil {
		return nil, err
	}
	return a.NewRecordBatch(), nil
}

// fixedArrowSchema is the Arrow schema of Fixed, resolved from its arrow
// struct tags.
var fixedArrowSchema = arrow.NewSchema([]arrow.Field{
	{Name: "ts", Type: &arrow.TimestampType{Unit: arrow.Nanosecond, TimeZone: "UTC"}, Nullable: false},
	{Name: "id", Type: arrow.PrimitiveTypes.Int64, Nullable: false},
	{Name: "val", Type: arrow.PrimitiveTypes.Float64, Nullable: false},
	{Name: "ok", Type: arrow.FixedWidthTypes.Boolean, Nullable: false},
	{Name: "opt", Type: arrow.PrimitiveTypes.Float64, Nullable: true},
}, nil)

// FixedSchema returns the Arrow schema encoded by FixedAppender.
func FixedSchema() *arrow.Schema { return fixedArrowSchema }

// FixedAppender converts Fixed values into Arrow record batches
// without reflection.
//
// It is not safe for concurrent use. Release it when done.
type FixedAppender struct {
	rb  *array.RecordBuilder
	b0  *array.TimestampBuilder
	b1  *array.Int64Builder
	b2  *array.Float64Builder
	b3  *array.BooleanBuilder
	b4  *array.Float64Builder
	err error
}

// NewFixedAppender returns an appender that builds Fixed batches with mem,
// or memory.DefaultAllocator when mem is nil. The typed field builders are
// resolved once here, so Append does no type assertions.
func NewFixedAppender(mem memory.Allocator) *FixedAppender {
	if mem == nil {
		mem = memory.DefaultAllocator
	}
	rb := array.NewRecordBuilder(mem, fixedArrowSchema)
	return &FixedAppender{
		rb: rb,
		b0: rb.Field(0).(*array.TimestampBuilder),
		b1: rb.Field(1).(*array.Int64Builder),
		b2: rb.Field(2).(*array.Float64Builder),
		b3: rb.Field(3).(*array.BooleanBuilder),
		b4: rb.Field(4).(*array.Float64Builder),
	}
}

// Schema returns the schema of the batches this appender builds.
func (a *FixedAppender) Schema() *arrow.Schema { return fixedArrowSchema }

// RecordBuilder returns the underlying builder. Appending through it directly
// is allowed as long as every column stays the same length.
func (a *FixedAppender) RecordBuilder() *array.RecordBuilder { return a.rb }

// Reserve pre-allocates room for n more rows in every column. Reserving before
// a run of Appends keeps the append path free of allocations.
func (a *FixedAppender) Reserve(n int) { a.rb.Reserve(n) }

// Len reports the number of rows appended since the last NewRecordBatch.
func (a *FixedAppender) Len() int { return a.rb.Field(0).Len() }

// Append appends one row. v is read synchronously and never retained, so a
// caller can reuse a single Fixed variable across calls.
func (a *FixedAppender) Append(v *Fixed) {
	a.b0.Append(arrow.Timestamp(v.Timestamp.UnixNano()))
	a.b1.Append(v.ID)
	a.b2.Append(v.Value)
	a.b3.Append(v.OK)
	if v.Optional == nil {
		a.b4.AppendNull()
	} else {
		a.b4.Append(*v.Optional)
	}
}

// AppendSlice appends every element of vs, reserving room for them up front.
func (a *FixedAppender) AppendSlice(vs []Fixed) {
	a.rb.Reserve(len(vs))
	for i := range vs {
		a.Append(&vs[i])
	}
}

// NewRecordBatch returns the appended rows as a record batch and resets the
// appender. The caller must Release the batch.
func (a *FixedAppender) NewRecordBatch() arrow.RecordBatch { return a.rb.NewRecordBatch() }

// Err returns the first error an Append hit, or nil. Only dictionary columns
// can fail. The error is sticky: NewRecordBatch does not clear it.
func (a *FixedAppender) Err() error { return a.err }

// Release releases the appender's builders.
func (a *FixedAppender) Release() { a.rb.Release() }

// FixedRecordBatch builds one record batch holding every element of vs. It is the
// generated equivalent of arreflect.RecordFromSlice[Fixed](vs, mem). The
// caller must Release the batch.
func FixedRecordBatch(mem memory.Allocator, vs []Fixed) (arrow.RecordBatch, error) {
	a := NewFixedAppender(mem)
	defer a.Release()
	a.AppendSlice(vs)
	if err := a.Err(); err != nil {
		return nil, err
	}
	return a.NewRecordBatch(), nil
}
